import {
  all,
  AsiaGaming,
  Booongo,
  CQ9,
  Evolution,
  HoGaming,
  PragmaticPlayLive,
  RedTigerGaming,
  SAGaming,
  Thunderkick,
  XProGaming,
  MascotGaming,
  NoLimitCity,
  OnlyPlay,
  PGSoft,
  PGSOFTSEAMLESS,
  PlaynGo,
  Quickspin,
  Yggdrasil,
  BoomingGames,
  GoldenHero,
  GreenJade,
  PragmaticPlay,
  BetSoft,
  EvoOSS,
  Ezugi,
  Fugaso,
  Habanero,
  KaGaming,
  Microgaming,
  PushGaming,
  RedRakeGaming,
  RelaxGaming,
  Spadegaming,
  Wazdan,
} from "@/assets/game_providers";
// 语言映射
const languageEnum = {
  ja: "ja-JP",
  en: "en-US",
};

// 游戏商图标
const iconGameProviders = {
  0: all,
  21: AsiaGaming,
  22: BetSoft,
  23: Booongo,
  24: CQ9,
  25: Evolution,
  26: EvoOSS,
  27: HoGaming,
  28: Microgaming,
  29: NoLimitCity,
  30: PGSoft,
  31: PlaynGo,
  _1: PragmaticPlayLive, // TUDO: 未确认

  34: PushGaming,
  35: RedTigerGaming,
  36: RelaxGaming,
  37: SAGaming,
  38: GoldenHero,
  39: Thunderkick,
  40: XProGaming,
  41: Yggdrasil,

  43: BoomingGames,
  44: Ezugi,
  45: Fugaso,
  46: GreenJade,
  47: Habanero,
  48: KaGaming,
  49: MascotGaming,
  50: OnlyPlay,
  51: Quickspin,
  52: RedRakeGaming,
  53: Spadegaming,
  54: Wazdan,
  91: PragmaticPlay,
  92: PGSOFTSEAMLESS,
};

export { languageEnum, iconGameProviders };
